baseurl: '/mcriviera'
include: ['_pages']
exclude: ['README.md', 'package.json', 'node_modules/', 'gulpfile.js', 'Gemfile', 'Gemfile.lock', 'CNAME']
includes_dir: ./_components
data_dir: ./_components
