t:
  en:
    SeoTitle: 'Monte Carlo Riviera'
    SeoAbout: 'Real Estate in Monaco and on the French Riviera'
    SeoDescription: "«Monte Carlo Riviera» LLC is the first company of Monaco's and French Riviera's real estate operating in the Ukrainian market on a straight line without intermediaries."
    HeaderBrand: 'Monte Carlo<span>Riviera</span>'
    HeaderLegalAdvice: 'Legal Advice on French Law'
    HeaderWeSpeek: 'Nous Parlons Français'
    HeaderContacts1: 'Pushkinskaya street 8A, of. 2<br>01001 Kyiv, Ukraine'
    HeaderContacts2: 'Monday - Friday: From 09:00 to 18:00<br>Saturday - Sunday: By appointment'
    HeaderContacts3: 'Mob .: +38 (067) 310-77-33<br>Tel. / Fax: +38 (044) 279-00-54'
    Hero1: 'Real Estate in Monaco and on the French Riviera'
    Hero2: "«Monte Carlo Riviera» LLC is the first company of Monaco's and French Riviera's real estate operating in the Ukrainian market on a straight line without intermediaries."
    CharacteristicsTitle: 'Characteristics of the tax system in Monaco:'
    Characteristics1: 'Lack of income tax (the only taxed citizens are from France and the United States)'
    Characteristics2: 'Lack of land tax and property tax, the lack of professional tax'
    Characteristics3: 'No tax on profits for companies who derive more than 75% of its revenue from operations in Monaco'
    Characteristics4: 'VAT: 20%, or 5.5%'
    Features1: 'All Kinds of Operations'
    Features2: 'Full Legal Support'
    Details1: 'We can offer you, not only a truly exclusive property segment of "luxury" in Monaco and the French Riviera, but also the provision of personalized services and individual approach to all your needs during transactions such as: legal advice on commercial, fiscal as well as corporate law in Monaco and France, support and translations during your visit to Monaco and more.'
    Details2: 'Despite the fact that Monaco symbolizes luxury and elegance, this country offers tranquility and optimum safety for its residents and their property.'
    Details3: 'More than 120 nationalities have chosen Monaco for all sorts of investments. The Principality of Monaco has an international reputation for dynamic and diversified economy as well as many financial platforms.'
    Details4: 'Monaco as an independent state in the heart of Europe that offers investors and foreign residents a unique lifestyle, security of investment, combined with the advantages of an attractive tax system. Therefore, if you decide to invest in Monaco, you will benefit from low taxation.'
    FooterCopyright: '© 2016<br>All rights reserved'
    FooterPowered: 'Powered by<span>Rooster Studio</span>'
  ru:
    SeoTitle: 'Монте Карло Ривьера'
    SeoAbout: 'Недвижимость в Монако и на Лазурном Берегу Франции'
    SeoDescription: 'Общество с ограниченной ответственностью «Монте Карло Ривьера» является первой компанией на украинском рынке работающей с недвижимостью в Монако и Лазурном Берегу Франции на прямую без посредников.'
    HeaderBrand: 'Монте Карло<span>Ривьера</span>'
    HeaderLegalAdvice: 'Юридичиские Консультации По Французскому Праву'
    HeaderWeSpeek: 'We Speak English, Nous Parlons Français'
    HeaderContacts1: 'ул. Пушкинская 8А, оф. 2<br>01001 г. Киев'
    HeaderContacts2: 'Понедельник – Пятница: С 09:00 До 18:00<br>Суббота – Воскресение: По Предварительной Записи'
    HeaderContacts3: 'моб.: +38 (067) 310-77-33<br>тел./факс: +38 (044) 279-00-54'
    Hero1: 'Недвижимость в Монако и на Лазурном Берегу Франции'
    Hero2: 'Общество с ограниченной ответственностью «Монте Карло Ривьера» является первой компанией на украинском рынке работающей с недвижимостью в Монако и Лазурном Берегу Франции на прямую без посредников.'
    CharacteristicsTitle: 'Характеристики налоговой системы в Монако:'
    Characteristics1: 'Отсутствие подоходного налога (налогом облагаются граждане Франции и США)'
    Characteristics2: 'Отсутствие земельного налога и налога на недвижимость, отсутствие профессионального налога'
    Characteristics3: 'Отсутствие налога на прибыль для предприятий, извлекающих более 75% своего дохода от операций на территории Монако'
    Characteristics4: 'НДС: 20% или 5,5%'
    Features1: 'Все Виды Операций'
    Features2: 'Полное Юридическое Сопровождение Сделок'
    Details1: 'Мы можем предложить Вам не только действительно эксклюзивною недвижимость сегмента “люкс” в Монако и на Лазурном Берегу, а так же  предоставление персонализированных услуг и индивидуальный подход ко всем Вашим потребностям во время совершения сделок: юридические консультации по коммерческому, фискальному а так же по корпоративному праву в Монако и во Франции, сопровождение и переводы во время Ваших визитов в Монако и многое другое.'
    Details2: 'Несмотря на то, что Монако символизирует роскошь и изысканность, эта страна предлагает спокойствие и оптимальную безопасность для его жителей и их имущества.'
    Details3: 'Более 120 национальностей выбрали Монако для разного рода инвестиций. Княжество Монако имеет международную репутацию динамичной и диверсифицированной экономики а так же множество финансовых платформ.'
    Details4: 'Монако в качестве независимого государства в центре Европы, предлагает инвесторам и иностранным жителям уникальный образ жизни, надежность инвестиций в сочетании с преимуществами привлекательной налоговой системы. Вкладывая деньги в Монако, Вы получаете выгоду от низкого налогообложения.'
    FooterCopyright: '© 2016<br>Все права защищены'
    FooterPowered: 'Powered by<span>Rooster Studio</span>'

