t:
  en:
    Brand: '«Monte-Carlo-Riviera» LLC'
    Feature0: 'Real Estate Abroad'
    Feature1: 'Real Estate in Monaco and on the French Riviera'
    Feature2: 'All Kinds of Operations'
    Feature3: 'Full Legal Support'
    Feature4: 'Legal Advice on French Law'
    WorkTime: 'Monday - Friday: From 09:00 to 18:00<br>Saturday - Sunday: By appointment<br>+38 (067) 310 77 33'
    WeSpeek: 'Nous Parlons Français'
    About1: "«Monte-Carlo-Riviera» LLC is the first company of Monaco's and French Riviera's real estate operating in the Ukrainian market on a straight line without intermediaries."
    About2: 'We can offer you, not only a truly exclusive property segment of "luxury" in Monaco and the French Riviera, but also the provision of personalized services and individual approach to all your needs during transactions such as: legal advice on commercial, fiscal as well as corporate law in Monaco and France, support and translations during your visit to Monaco and more.'
    About3: 'Despite the fact that Monaco symbolizes luxury and elegance, this country offers tranquility and optimum safety for its residents and their property.'
    About4: 'More than 120 nationalities have chosen Monaco for all sorts of investments. The Principality of Monaco has an international reputation for dynamic and diversified economy as well as many financial platforms.'
    About5: 'Monaco as an independent state in the heart of Europe that offers investors and foreign residents a unique lifestyle, security of investment, combined with the advantages of an attractive tax system. Therefore, if you decide to invest in Monaco, you will benefit from low taxation.'
    ListTitle: 'Characteristics of the tax system in Monaco:'
    Li1: 'Lack of income tax (the only taxed citizens are from France and the United States)'
    Li2: 'Lack of land tax and property tax, the lack of professional tax'
    Li3: 'No tax on profits for companies who derive more than 75% of its revenue from operations in Monaco'
    Li4: 'VAT: 20%, or 5.5%'
    WeLocated: 'We are located at:'
    Contacts: 'Pushkinskaya street 8A, of. 2<br>01134 Kyiv, Ukraine<br>Mob .: +38 (067) 310-77-33<br>Tel. / Fax: +38 (044) 279-00-54'
  ru:
    Brand: 'ООО «Монте-Карло-Ривьера»'
    Feature0: 'Агентство Зарубежной Недвижимости'
    Feature1: 'Недвижимость в Монако и на Лазурном Берегу Франции'
    Feature2: 'Все Виды Операций'
    Feature3: 'Полное Юридическое Сопровождение Сделок'
    Feature4: 'Юридичиские Консультации По Французскому Праву'
    WorkTime: 'Понедельник – Пятница: С 09:00 До 18:00<br>Суббота – Воскресение: По Предварительной Записи<br>+38 (067) 310 77 33'
    WeSpeek: 'We Speak English, Nous Parlons Français'
    About1: 'Общество с ограниченной ответственностью «Монте-Карло-Ривьера» является первой компанией на украинском рынке работающей с недвижимостью в Монако и Лазурном Берегу Франции на прямую без посредников.'
    About2: 'Мы можем предложить Вам не только действительно эксклюзивною недвижимость сегмента “люкс” в Монако и на Лазурном Берегу, а так же  предоставление персонализированных услуг и индивидуальный подход ко всем Вашим потребностям во время совершения сделок: юридические консультации по коммерческому, фискальному а так же по корпоративному праву в Монако и во Франции, сопровождение и переводы во время Ваших визитов в Монако и многое другое.'
    About3: 'Несмотря на то, что Монако символизирует роскошь и изысканность, эта страна предлагает спокойствие и оптимальную безопасность для его жителей и их имущества.'
    About4: 'Более 120 национальностей выбрали Монако для разного рода инвестиций. Княжество Монако имеет международную репутацию динамичной и диверсифицированной экономики а так же множество финансовых платформ.'
    About5: 'Монако в качестве независимого государства в центре Европы, предлагает инвесторам и иностранным жителям уникальный образ жизни, надежность инвестиций в сочетании с преимуществами привлекательной налоговой системы. Вкладывая деньги в Монако, Вы получаете выгоду от низкого налогообложения.'
    ListTitle: 'Характеристики налоговой системы в Монако:'
    Li1: 'Отсутствие подоходного налога (налогом облагаются граждане Франции и США)'
    Li2: 'Отсутствие земельного налога и налога на недвижимость, отсутствие профессионального налога'
    Li3: 'Отсутствие налога на прибыль для предприятий, извлекающих более 75% своего дохода от операций на территории Монако'
    Li4: 'НДС: 20% или 5,5%'
    WeLocated: 'Мы находимся по адресу:'
    Contacts: 'ул. Пушкинская 8А, оф. 2<br>01134 г. Киев<br>моб.: +38 (067) 310-77-33<br>тел./факс: +38 (044) 279-00-54'

